plugins {
    id 'java'
    id 'groovy'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Forge Maven'
        url = 'https://maven.minecraftforge.net/'
    }
    maven { url "https://maven.architectury.dev/" }
    maven { url "https://maven.fabricmc.net/" }
    mavenLocal()
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation gradleApi()
    implementation localGroovy()

    implementation libs.asm.commons
    implementation libs.asm.tree
    implementation libs.asm.util
    implementation libs.commons.io

    implementation libs.loom
    implementation libs.tiny.remapper
    implementation libs.lorenz.core
    implementation libs.lorenz.proguard
    implementation libs.lorenz.tiny
    implementation libs.mercury
    implementation libs.at

    implementation(libs.specialsource) { transitive false }

}